name: happiness_jar
description: "Happiness jar project."

publish_to: 'none'

version: 1.8.0+36

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  iconly: ^1.0.1
  provider: ^6.1.1
  get_it: ^7.2.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  auto_size_text: ^3.0.0
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  sqflite: ^2.0.2
  path: ^1.8.0
  easy_localization: ^3.0.0
  share_plus: ^10.1.4
  clipboard: ^0.1.3
  top_snackbar_flutter: ^3.1.0
  image_picker: ^0.8.4+3
  path_provider: ^2.1.3
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.3.4
  firebase_analytics: ^11.4.4
  firebase_messaging: ^15.1.3
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  in_app_review: ^2.0.9
  lottie: ^1.2.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  screenshot: ^3.0.0
  google_mobile_ads: ^5.1.0
  flutter_fortune_wheel: ^1.3.1
  cached_network_image: ^3.3.1
  flutter_local_notifications: ^17.2.2
  badges: ^3.1.2
  vision_gallery_saver: ^2.0.2
  audio_waveforms: ^1.3.0
#  flutter_native_splash: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/icons/logo.png"
#  remove_alpha_ios: false

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/animations/
    - assets/svgs/

  fonts:
    - family: bar
      fonts:
        - asset: assets/fonts/bar.ttf
    - family: avenir_bold
      fonts:
        - asset: assets/fonts/avenir_bold.otf
    - family: avenir_regular
      fonts:
        - asset: assets/fonts/avenir_regular.otf
    - family: avenir_medium
      fonts:
        - asset: assets/fonts/avenir_medium.otf